baseURL: https://parkour..ch/
title: parkour.ch

languageCode: fr-ch
defaultContentLanguage: fr

canonifyURLs: true
copyright: Nicolas Friedli
disableFastRender: true
disableFastRender: true
# enableGitInfo: true
cleandestinationdir: true
removePathAccents: true

author:
  name: Nicolas Friedli
  email: nicolasfriedli@protonmail.ch

disableKinds:
  - 404
  - sitemap
  - RSS

related:
  includeNewer: true
  indices:
  - name: korper
    weight: 50
  - name: psyche
    weight: 50
  - name: kreativitat
    weight: 50
  - name: personlichkeit
    weight: 50
  threshold: 80
  toLower: true

taxonomies:
  korper: korper
  psyche: psyche
  kreativitat: kreativitat
  personlichkeit: personlichkeit

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  footer: |
    **Site en développement!**  